### ISSUE TITLE
Automate AWS environment creation

### ISSUE THREAD

**Issue by revmischa** [revmischa/cloudcam#1]
Goal: make it easy for a developer or user to create or upgrade their AWS environment to run a CloudCam service.
Long-term goal: make a package that can be sold and easily deployed from [AWS Marketplace](https://aws.amazon.com/marketplace/management/tour/).

Some components will probably be: IAM roles, Lambdas, Step Functions, S3 bucket, IoT (Thing category, rules), API gateway, RDS (PostgreSQL Aurora). 
In future maybe Greengrass, X-ray, Rekognition, Elastic Transcoder, Cognito, Glacier, WAF/Shield, CloudWatch metrics.

I suggest using CloudFormation.

**Comment by someone--else** [comment]
I suppose this could be closed now since the initial CloudFormation setup is done
