### ISSUE TITLE
Janus hosting

### ISSUE THREAD

**Issue by revmischa** [revmischa/cloudcam#3]
- [x] Find somewhere to run dockerized Janus with DTLS support (lightsail?).
- [x] Create a service registry of Janus instances available for usage - integrating cloudwatch health checks and/or ELB would be cool. Maybe use PostgreSQL, DynamoDB or consul?
- [x] Need secret storage for certs (https://aws.amazon.com/certificate-manager/ or Vault or KMS ?))

**Comment by someone--else** [comment]
Re: service registry: currently running Janus instance list is produced via Lightsail API query so there's currently no need for a separate store like DynamoDB
