### ISSUE TITLE
Janus Cloudcam Plugin

### ISSUE THREAD

**Issue by revmischa** [revmischa/cloudcam#5]
I imagine we will need a custom Janus plugin for cloudcam to handle registration of mountpoints and relaying status to cloudcam.
This is just an assumption though - maybe the existing API and streaming plugin provide enough functionality for us? Except for lack of SRTP support

**Comment by someone--else** [comment]
Currently existing API/streaming plugin works fine, so I think there's no immediate need for this (SRTP would be addressed separately in #6)

**Comment by revmischa** [comment]
Okay. I assumed we might want to store some cloudcam identifiers on streams/mountpoints in Janus to make integration easier, or handle access control

**Comment by someone--else** [comment]
We use stream name for that, seems enough. Access control is supposed to work via stream secrets/pins (this needs some more testing across browsers)

**Comment by someone--else** [comment]
Perhaps a more fine-grained control would warrant a plugin in the future, however now the possible benefits are somewhat theoretical while plugin maintenance will definitely require some time
