### ISSUE TITLE
Serverless transforms

### ISSUE THREAD

**Issue by revmischa** [revmischa/cloudcam#8]
If it will be beneficial, we should convert the cloudformation templates to use the new Serverless transforms which should make them more concise. 

https://github.com/awslabs/serverless-application-model

https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31

**Comment by someone--else** [comment]
Done; though roles/policies for most lambdas are still set up separately since AssumeRolePolicyDocument isn't seemingly available via AWS::Serverless::Function
